repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: debug-statements

  - repo: https://github.com/python-poetry/poetry
    rev: 1.3.2
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
        args:
          - --without-hashes
          - -f
          - requirements.txt

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.0.1
    hooks:
     - id: autoflake
       name: autoflake
       entry: autoflake
       language: python
       require_serial: true
       args:
         - --recursive
         - --in-place
         - --expand-star-imports
         - --remove-duplicate-keys
         - --remove-unused-variables
         - --remove-all-unused-imports
         - --ignore-init-module-imports

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v7.30.0
    hooks:
      - id: eslint

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--profile, black]

  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
