# Generated by Django 5.0.4 on 2024-05-04 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("paginas", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="funcionariomodels",
            options={
                "verbose_name": "Funcionario",
                "verbose_name_plural": "Funcionarios",
            },
        ),
    ]
