# Generated by Django 5.0.4 on 2024-05-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmpresaModels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_empresa", models.CharField(max_length=30, verbose_name="Nome")),
                (
                    "logo_empresa",
                    models.ImageField(upload_to="imagens_empresa", verbose_name="Logo"),
                ),
                (
                    "instagram_empresa",
                    models.CharField(
                        default=None, max_length=255, verbose_name="Instagram"
                    ),
                ),
                (
                    "whatsapp_empresa",
                    models.CharField(
                        default=None, max_length=11, verbose_name="WhatsApp"
                    ),
                ),
                (
                    "facebook_empresa",
                    models.CharField(
                        default=None, max_length=255, verbose_name="Facebook"
                    ),
                ),
                (
                    "youtube_empresa",
                    models.CharField(
                        default=None, max_length=255, verbose_name="YouTube"
                    ),
                ),
            ],
            options={
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresa",
            },
        ),
    ]
