# Generated by Django 5.0.4 on 2024-05-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresa", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empresamodels",
            name="facebook_empresa",
            field=models.CharField(
                default=None, max_length=255, null=True, verbose_name="Facebook"
            ),
        ),
        migrations.AlterField(
            model_name="empresamodels",
            name="instagram_empresa",
            field=models.CharField(
                default=None, max_length=255, null=True, verbose_name="Instagram"
            ),
        ),
        migrations.AlterField(
            model_name="empresamodels",
            name="whatsapp_empresa",
            field=models.CharField(
                default=None, max_length=11, null=True, verbose_name="WhatsApp"
            ),
        ),
        migrations.AlterField(
            model_name="empresamodels",
            name="youtube_empresa",
            field=models.CharField(
                default=None, max_length=255, null=True, verbose_name="YouTube"
            ),
        ),
    ]
