# Generated by Django 5.0.4 on 2024-05-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresa", "0002_alter_empresamodels_facebook_empresa_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empresamodels",
            name="facebook_empresa",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="Facebook",
            ),
        ),
        migrations.AlterField(
            model_name="empresamodels",
            name="instagram_empresa",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="Instagram",
            ),
        ),
        migrations.AlterField(
            model_name="empresamodels",
            name="whatsapp_empresa",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=11,
                null=True,
                verbose_name="WhatsApp",
            ),
        ),
        migrations.AlterField(
            model_name="empresamodels",
            name="youtube_empresa",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="YouTube",
            ),
        ),
    ]
